version: '3'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
    ports:
      - ${DOCKER_APACHE2_PORT}:80
    container_name: ${DOCKER_CONTAINER_NAME}-php
    environment:
      DB_PORT: 3306
      DB_HOST: database
      XDEBUG_CONFIG: "remote_host=${DOCKER_APACHE2_XDEBUG_IP} remote_enable=1 remote_mode=req remote_port=9000 remote_connect_back=0 idekey=PHPSTORM extended_info=1"
          #XDEBUG_CONFIG: "remote_host=192.168.1.100 remote_enable=1 remote_mode=req remote_port=9000 remote_connect_back=0 idekey=PHPSTORM extended_info=1"
      PHP_IDE_CONFIG: "serverName=${DOCKER_CONTAINER_NAME}"
      PHP_XDEBUG_ENABLED: "1"

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - ./dbdata:/var/lib/mysql
    container_name: ${DOCKER_CONTAINER_NAME}-mysql
    environment:
      MYSQL_DATABASE: forge
      MYSQL_USER: forge
      MYSQL_PASSWORD: fprgepwd
      MYSQL_ROOT_PASSWORD: rootpwd123
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
volumes:
  dbdata:
